module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/scripts', '<rootDir>/src/security', '<rootDir>/src/ai', '<rootDir>/src/fhir'],
  testMatch: ['**/__tests__/**/*.ts', '**/?(*.)+(spec|test).ts'],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'scripts/**/*.ts',
    'core/**/*.ts',
    'src/security/**/*.ts',
    'src/ai/**/*.ts',
    'src/fhir/**/*.ts',
    '!**/*.test.ts',
    '!**/node_modules/**',
    '!**/dist/**',
    '!**/examples.ts',
    '!**/secureExamples.ts',
    '!**/provider-access-examples.ts',
    '!**/cli/**',
    '!**/utils/template-helpers.ts',
    '!**/utils/generate-*.ts',
    '!**/generate-synthetic-bulk-data.ts',
    '!**/payer-to-payer-example.ts',
    '!**/prior-auth-api.ts',
    '!**/payer-to-payer-api.ts',
    '!**/x12Types.ts',
  ],
  coverageThreshold: {
    global: {
      branches: 73,
      functions: 80,
      lines: 80,
      statements: 80,
    },
  },
  moduleFileExtensions: ['ts', 'tsx', 'js', 'jsx', 'json', 'node'],
};
