
name: Deploy 275 Attachments (Bicep + Logic Apps)

on:
  workflow_dispatch:
    inputs:
      subscriptionId:
        description: 'Azure Subscription ID'
        required: true
      resourceGroup:
        description: 'Resource Group name (will be created if missing)'
        required: true
        default: '275-attachments-rg'
      location:
        description: 'Azure region'
        required: true
        default: 'eastus'
      baseName:
        description: 'Base name prefix for resources'
        required: true
        default: '275-attachments'
      logicAppName:
        description: 'Logic App Standard app name (optional; defaults to <baseName>-la)'
        required: false
        default: ''
      bicepPath:
        description: 'Path to Bicep file'
        required: true
        default: 'infra/main.bicep'
      workflowsPath:
        description: 'Path to Logic App workflows folder (must contain subfolders per workflow with workflow.json inside)'
        required: true
        default: 'logicapps/workflows'

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ github.event.inputs.subscriptionId }}

      - name: Ensure Resource Group
        uses: azure/cli@v2
        with:
          inlineScript: |
            az group create -n "${{ github.event.inputs.resourceGroup }}" -l "${{ github.event.inputs.location }}"

      - name: Deploy Bicep (infra)
        uses: azure/arm-deploy@v2
        with:
          scope: resourcegroup
          resourceGroupName: ${{ github.event.inputs.resourceGroup }}
          template: ${{ github.event.inputs.bicepPath }}
          parameters: baseName=${{ github.event.inputs.baseName }}
          deploymentName: 275-attachments-infra

      - name: Resolve Logic App name
        id: resolvela
        uses: azure/cli@v2
        with:
          inlineScript: |
            LA="${{ github.event.inputs.logicAppName }}"
            if [ -z "$LA" ]; then
              LA="${{ github.event.inputs.baseName }}-la"
            fi
            echo "name=$LA" >> $GITHUB_OUTPUT

      - name: Zip Logic App workflows
        run: |
          set -euo pipefail
          cd "${{ github.event.inputs.workflowsPath }}"
          # Expect structure: logicapps/workflows/<workflowName>/workflow.json
          zip -r ../../workflows.zip .
          cd -
          ls -l logicapps/workflows ../../workflows.zip || true

      - name: Deploy workflows (ZIP deploy to Logic App Standard)
        uses: azure/cli@v2
        with:
          inlineScript: |
            APP="${{ steps.resolvela.outputs.name }}"
            RG="${{ github.event.inputs.resourceGroup }}"
            ZIP_PATH="workflows.zip"
            if [ ! -f "$ZIP_PATH" ]; then
              echo "::error::ZIP $ZIP_PATH not found. Ensure previous step created it."; exit 1
            fi
            # Deploy zip to site root; Logic Apps Standard expects 'workflows/<name>/workflow.json' structure
            az webapp deploy               --resource-group "$RG"               --name "$APP"               --src-path "$ZIP_PATH"               --type zip

      - name: Restart Logic App to pick up new workflows (optional)
        uses: azure/cli@v2
        with:
          inlineScript: |
            az webapp restart -g "${{ github.event.inputs.resourceGroup }}" -n "${{ steps.resolvela.outputs.name }}"
